apiVersion: apps/v1
kind: Deployment
metadata:
  name: sartsigithubio-deployment
  labels:
    app: sartsigithubio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sartsigithubio
  template:
    metadata:
      labels:
        app: sartsigithubio
    spec:
      containers:
      - name: sartsigithubio
        image: sartsi/sartsigithubio-arm64:1.0.2
        ports:
        - containerPort: 80

