name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    environment: docker
    env:
      DOCKER_TOKEN: ${{ env.DOCKER_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export;
        export CURRENT_TAG_NAME=$(date +%s); docker build . --file Dockerfile --tag sartsi/sartsigithubio:$CURRENT_TAG_NAME; docker login -u sartsi -p ${{ env.DOCKER_ACCESS_TOKEN }}; docker push sartsi/sartsigithubio:$CURRENT_TAG_NAME
        
