name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    #environment: docker
    steps:
    - with:
        DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export;
        echo $DOCKER_TOKEN;
        export CURRENT_TAG_NAME=$(date +%s); docker build . --file Dockerfile --tag sartsi/sartsigithubio:$CURRENT_TAG_NAME; docker login -u sartsi -p ${{ secrets.DOCKER_ACCESS_TOKEN }}; docker push sartsi/sartsigithubio:$CURRENT_TAG_NAME
        
